### ISSUE TITLE
Getting Started Dev Templates

### ISSUE THREAD

**Issue by fhalin** [nextmoov/nextmoov#1]
-[] nodejs vanilla esNext
-[] nodejs vanilla esNext + express
-[] F-E vanilla esNext
-[] F-E vanilla esNext + react
-[] F-E vanilla esNext + react+ redux

**Comment by thomashermine** [comment]
Interesting read : https://loremipsum.ueno.co/new-year-a-new-tech-stack-37dca10735a5

**Comment by denisflorkin** [comment]
First draft (node, node-express, react)

https://github.com/nextmoov/cjx

Try it => `npx cjx`

**Comment by thomashermine** [comment]
Now replace by MOAR — https://github.com/nextmoov/moar
