### ISSUE TITLE
Standard entrypoint: yarn start, yarn start:production

### ISSUE THREAD

**Issue by thomashermine** [nextmoov/nextmoov#15]
# Standard EntryPoint 

```yarn start``` Run the project in *Development*
```yarn build``` Build the static assets to be served in production in /dist

# Archived Discussion

I would like to standardize the entrypoint for Front & Back project, for both Production & Development.

I hereby propose that all our project (back & front) follow this convention:

```yarn start``` Run the project in *Development*
```yarn serve``` Run the project in *Production* (serve precompiled assets in /dist)

#### Why not yarn start in Production?

Create-React-App (and actually a lot of other framework) use ```yarn start``` as the entrypoint for Development — I propose that we don't override this behaviour

**Comment by thomashermine** [comment]
Up @antony-funquality @ferrarisMat 
Needed to be set in CJX by @denisflorkin

**Comment by antony-funquality** [comment]
My position is:
`yarn start` for dev
`yarn build` and served with Nginx on production

@denisflorkin Take care that we have choosen to only use `yarn` and not `npm` anymore.

**Comment by thomashermine** [comment]
@denisflorkin Could you agree on this as well, so we can close this issue?

`
# Standard EntryPoint 

```yarn start``` Run the project in *Development*
```yarn build``` Build the static assets to be served in production in /dist`
