### ISSUE TITLE
Base branch : Develop or master? Locking?

### ISSUE THREAD

**Issue by thomashermine** [nextmoov/nextmoov#24]
The Great Migration 🦜*... is coming! 

I have 2 related questions for you guys before we can proceed : 

### 1. Base Branch : Develop

**We decided to use Develop as Base Branch**

What Base branch should we pick for every project? 

_Develop_ : Will show every Issue as closed as soon as their related PR is merged to develop (and thus deployed to staging *but not to production*, which can be confusing for the PM/end-users)

_Master_ : Will show every Issue as closed as soon as they are released to production (but thus still open after their PR as been merged, which can be confusing for the dev)

### 2. Locking

Should we use a [locking strategy](https://help.github.com/en/articles/defining-the-mergeability-of-pull-requests) on Develop and Master branches? 
If so, which one?

**We decided to use this configuration:**

<img width="563" alt="Screenshot 2019-04-17 at 16 57 21" src="https://user-<img width="496" alt="Screenshot 2019-04-18 at 15 01 07" src="https://user-images.githubusercontent.com/4315469/56362750-e4c70300-61ea-11e9-9283-673075754395.png">

<img width="480" alt="Screenshot 2019-04-18 at 14 59 17" src="https://user-images.githubusercontent.com/4315469/56362716-d5e05080-61ea-11e9-85a2-b2b915562301.png">

> \* The Great Migration 🦜is the name of our move from BitBucket to GitHub, as well as the use of a PR-based flow on every projects.

**Comment by denisflorkin** [comment]
Dismis stale pull request approvals when new commits should be checked IMHO

And yes I would make the develop and master 'protected'.

Altho, I would still allow admin to merge (everybody can be admin) just in case some monkey patching is needed, this way you can't push accidentaly
BUT you still have the ability to force merge somerthing (but not force push)

**Comment by thomashermine** [comment]
### 1. Base branch

@denisflorkin @fhalin Any feedback?

### 2. Locking

@denisflorkin Totally agree with you, here is the setup I'm going to deploy on every repo 💯 
<img width="496" alt="Screenshot 2019-04-18 at 15 01 07" src="https://user-images.githubusercontent.com/4315469/56362750-e4c70300-61ea-11e9-9283-673075754395.png">

<img width="480" alt="Screenshot 2019-04-18 at 14 59 17" src="https://user-images.githubusercontent.com/4315469/56362716-d5e05080-61ea-11e9-85a2-b2b915562301.png">

**Comment by fhalin** [comment]
I vote for base branch = develop :)

**Comment by thomashermine** [comment]
Thanks guys! Closing for now, and I'm preparing a How To which mentions theses defaults :
https://github.com/nextmoov/nextmoov/pull/26
