### ISSUE TITLE
Zube - Default Config

### ISSUE THREAD

**Issue by thomashermine** [nextmoov/nextmoov#29]
As we have more and more projects on Zube, we need to enforce the same settings on every project.

Could we agree on this config? 

- **Name** : client-project OR p-client-project ?
- **Columns** : 
<img width="1040" alt="Screenshot 2019-05-01 at 15 03 55" src="https://user-images.githubusercontent.com/4315469/57018148-8c4c2880-6c22-11e9-8eb1-f21fbfb2143a.png">

**Comment by thomashermine** [comment]
@fhalin Up :)

**Comment by fhalin** [comment]
Agreed with the above! On top of that, I would propose the following workspace settings:
- **Enable** auto archive of PR
- **Enable** column labels
- **Enable** priorities, with categories Blocker, Critical, ...
- **Disable** points
- **Disable** upvotes
As for the workspace and naming conventions, I propose the following:
- **One Zube project per project**, named as *client-project*
- **One workspace with integration of all project-related GitHub repos** to allow for an overview of the work of all parties (backend, frontend, PM, design ...).
Finally, I propose to **enforce the use of the Sprint views** for planning purpose, while the definition of Epics is left to the need of every project.

**Comment by itardis13** [comment]
- Naming : client-project
- Agreed on columns, this is what I did on Stoomink

Agreed with @fhalin propositions.
- Do we have to keep the Epics ?

**Comment by fhalin** [comment]
As said, for me it is up to the complexity of the project mostly. It allows for dedicated view per macro-components but that's pretty much it :)
On the longer run, it could also allow for easier set-up of project based on similar previous Epics.

**Comment by itardis13** [comment]
Good 4 me. Move to done? ;)
Stoomlink's workspaces have been adapted.

**Comment by fhalin** [comment]
Je vais la fermer quand je l'aurai incluse dans un guide PO/PM ici :)
