### ISSUE TITLE
The Great Migration 🦜

### ISSUE THREAD

**Issue by fhalin** [nextmoov/nextmoov#3]
[EDIT by @thomashermine ]

**This is the beginning of The Great Migration 🦜**

Current status: 

- [ ] Ops : 
  - [x] Update Drone, set to connect to GitHub instead of BitBucket
- [ ] Repository : Migrate all the things! ✊
  - [x] cambio
    - [x] cambio-start-web
    - [x] cambio-start-app
    - [x] cambio-registration-middleware
  - [x] modalizy
    - [x] modalizy-app-app
    - [x] modalizy-services-api
    - [x] modalizy-services-etl
    - [x] modalizy-notifications-middleware
    - [x] modalizy-signing
  - [x] nextmoov-ticketing
    - [x] nextmoov-ticketing-api
  - [x] smb-pto
    - [x] smb-pto-frontend

**Comment by thomashermine** [comment]
@antony-funquality Could you confirm we don't have any repository left for SMB-PTO on BitBucket?

**Comment by antony-funquality** [comment]
> @antony-funquality Could you confirm we don't have any repository left for SMB-PTO on BitBucket?

I can confirm that all functional SMOP modules as been migrated, but not sure about the DevOps and other tools.

**Comment by thomashermine** [comment]
Dear all, I'm more than happy to announce that... everything has been migrated! 🙌 
Welcome to your new home, Zube & GitHub! :-)
