### ISSUE TITLE
Time Tracking

### ISSUE THREAD

**Issue by thomashermine** [nextmoov/nextmoov#9]
Currently tested flow :

### Billed Hours Tracking
— Tag in Zube/GitHub issue : 
- S (4 hours)
- M (8 hours)
- L (16 hours)
- XL (32 hours)

Above 32 hours : split the story

### Effective Hours Tracking

Time tracking in any Commit Message : 
```
fixes #99
spent 00:00
```

Ressources : 
https://gitlab.com/gitlab-org/gitlab-ce/issues/28044
https://github.com/timeglass/glass

+  Dedicated Backend (GitHub App)
- Consolidate all data from commit messages 
- Allow adding a custom row for time not-related to a commit (PM,...)
- Could evolves towards a full dashboard for the company (tracking margin per project/client/freelance/...)

**Comment by denisflorkin** [comment]
Regarding format in commit message, I am assuming js will evaluate this at some point, might I suggest a moment.js recognisable format

```js
moment.duration('01:30'); 
// or even without padding 
moment.duration('1:30');
```

https://momentjs.com/docs/#/durations/ ("ASP.NET style time spans" section)

https://runkit.com/embed/sv4dqg2wgse8

the template for commit msg could be 
```
\n
spent: <value>\n
```

e.g.

```
#99 - Fix button radius

  needed to upgrade deps

  spent: 4:30

  maybe more stuff here
```

**Comment by thomashermine** [comment]
PSA to all Devs ! :-)
@denisflorkin is currently working on an awesome dashboard to consolidate time tracking. 

This :
https://github.com/nextmoov/nextmoov/issues/9#issue-427062164

... shall be enforced, starting now.

It will *not* have an impact on invoicing (as of today, Freelancers, please keep maintaining your own timesheet) as it's only a Beta :-)

But, so that this Beta can be effective, please start add the magic command:
> spent 00:00 

(In that specific format, 00:00 — not 0h00, 00h00,...)

... on every commit :-)
